/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Fraunces"', "serif"],
        sans: ['"Plus Jakarta Sans"', "ui-sans-serif", "system-ui", "sans-serif"],
        script: ['"Caveat"', "cursive"],
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        paradise: {
          blue: "#0052FF",       // electric primary
          blueDark: "#0034B0",
          navy: "#0A1F66",
          cyan: "#00B4FF",
          cyanSoft: "#E6F7FF",
          yellow: "#FFD60A",
          yellowDark: "#F5B800",
          green: "#00C896",
          greenDark: "#00A07B",
          coral: "#FF5E5B",
          cream: "#FFFBF0",
          ink: "#0A1A2F",
          slate: "#4A5878",
          mist: "#F5F8FF",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-up": { "0%": { opacity: "0", transform: "translateY(16px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "float-slow": { "0%,100%": { transform: "translateY(0) rotate(0deg)" }, "50%": { transform: "translateY(-12px) rotate(2deg)" } },
        "marquee": { "0%": { transform: "translateX(0)" }, "100%": { transform: "translateX(-50%)" } },
        "bounce-x": { "0%,100%": { transform: "translateX(0)" }, "50%": { transform: "translateX(8px)" } },
        "shine": { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        "pulse-ring": { "0%": { transform: "scale(0.95)", opacity: "0.6" }, "70%": { transform: "scale(1.4)", opacity: "0" }, "100%": { transform: "scale(1.4)", opacity: "0" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-up": "fade-up 0.7s cubic-bezier(0.2, 0.8, 0.2, 1) both",
        "float-slow": "float-slow 6s ease-in-out infinite",
        "marquee": "marquee 30s linear infinite",
        "bounce-x": "bounce-x 1.4s ease-in-out infinite",
        "shine": "shine 3s linear infinite",
        "pulse-ring": "pulse-ring 2.2s cubic-bezier(0.215, 0.610, 0.355, 1) infinite",
      },
      boxShadow: {
        soft: "0 8px 30px rgba(10,31,102,0.08)",
        hover: "0 24px 50px rgba(0,82,255,0.18)",
        glass: "0 8px 32px rgba(0,82,255,0.10)",
        vibrant: "0 16px 40px -8px rgba(0,82,255,0.4)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
